### ISSUE TITLE
RangeError: length > kMaxLength

### ISSUE THREAD

**Issue by ldng** [zont/gulp-bower#24]
I just have a task that install the bower components :
```javascript
gulp.task('trans-js-libs-bower', function() {
    return bower({ directory: '.', cwd: srcPaths.libs });
});
```

where srcPaths.libs is src/js/libs and contains a bower.json

```bash
[18:13:54] Starting 'trans-js-libs-bower'...
[18:13:54] Using cwd:  src/js/libs
[18:13:54] Using bower dir:  .

buffer.js:194
      this.parent = new SlowBuffer(this.length);
                    ^
RangeError: length > kMaxLength
    at new Buffer (buffer.js:194:21)
    at fs.js:222:16
    at Object.oncomplete (fs.js:107:15)
```

Haven't looked at it in depth yet. It's probably me misusing the task
but I'm reporting it just in case it might be a real bug.

**Comment by zont** [comment]
Looks like fs module bug. Can you make complete test?
