### ISSUE TITLE
Error in module

### ISSUE THREAD

**Issue by volodymyrl** [zont/gulp-bower#36]
When I run a gulp task (use first examle from this page https://www.npmjs.com/package/gulp-bower) I got an error

Using bower dir:  ./bower_components

[21:01:16] Using bower dir:  ./bower_components

D:\temp\node_modules\gulp-bower\node_modules\bower\node_modules\q\q.js:128
                    throw e;
                          ^
SyntaxError: Unexpected token }
    at Object.parse (native)
    at D:\temp\node_modules\gulp-bower\node_modules\bower\node_modules\bower-json\lib\json.js:41:29
    at fs.js:272:14
    at D:\temp\node_modules\gulp-bower\node_modules\bower\node_modules\bower-json\node_modules\graceful-fs\graceful-fs.js:104:5
    at D:\temp\node_modules\gulp-bower\node_modules\bower\node_modules\bower-registry-client\node_modules\graceful-fs\graceful-fs.js:104:5
    at D:\temp\node_modules\gulp-bower\node_modules\bower\node_modules\bower-config\node_modules\graceful-fs\graceful-fs.js:104:5
    at Object.oncomplete (fs.js:108:15)

**Comment by volodymyrl** [comment]
Reason was in addition comma in bower.json
