### ISSUE TITLE
Empty .bowerrc causes unexpected SyntaxError

### ISSUE THREAD

**Issue by narthollis** [zont/gulp-bower#43]
When my .bowerrc file is empty, I get an unexpected SyntaxError.

As bower is able to ignore the file in this state, It would be desirable for gulp-bower to also ignore the file in this state.

	[11:35:42] SyntaxError: Unexpected end of input
		at Object.parse (native)
		at module.exports (C:\...\node_modules\gulp-bower\index.js:29:28)
		at Gulp.<anonymous> (C:\...\Gulpfile.js:14:9)
		at module.exports (C:\...\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
		at Gulp.Orchestrator._runTask (C:\...\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
		at Gulp.Orchestrator._runStep (C:\...\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
		at Gulp.Orchestrator.start (C:\...\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
		at C:\...\node_modules\gulp\bin\gulp.js:129:20
		at process._tickCallback (node.js:419:13)
		at Function.Module.runMain (module.js:499:11)
	Process terminated with code 1.

**Comment by zont** [comment]
Fixed in #49
