### ISSUE TITLE
TypeError: current.restore is not a function

### ISSUE THREAD

**Issue by bflorat** [zont/gulp-bower#46]
Hi there, 
Context : 
* bower 1.7.0
* gulp-bower : 0.0.11
* gulp 3.9.0

My Gulp file : 
```
gulp.task('bower', function() {
  return bower()
	  .pipe(gulp.dest('lib/'))
});
```

result of a ``gulp bower`` :

```
***\node_modules\q\q.js:155
				throw e;
				^

TypeError: current.restore is not a function
	at Function.restoreConfig [as restore] (****\node_modules\bower\lib\config.js:56:17)
	at ****\node_modules\bower\lib\commands\index.js:67:20
	at _rejected (****\node_modules\q\q.js:844:24)
	at ****\node_modules\q\q.js:870:30
	at Promise.when (****\node_modules\q\q.js:1122:31)
	at Promise.promise.promiseDispatch (****\node_modules\q\q.js:788:41)
	at ****\node_modules\q\q.js:556:49
	at runSingle (****\node_modules\q\q.js:137:13)
	at flush (****\node_modules\q\q.js:125:13)
	at nextTickCallbackWith0Args (node.js:433:9)
```
Any idea ?

**Comment by anotomix** [comment]
Just upgrade your bower version:
[code]npm install -g bower[/code]

**Comment by zont** [comment]
it is not gulp-bower bug.
